services:
  db:
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./build/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  city-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - CITY_API_DB_URL=jdbc:postgresql://db:5432/city_api
    ports:
      - "2022:2022"
    depends_on:
      - db


volumes:
  db_data:
