---
name: Renovate

"on":
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
